#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.23f1_3f4e01f1a5ec"
#define UNITY_VERSION_FULL_NICE "2019.4.23f1 (3f4e01f1a5ec)"
#define UNITY_VERSION_BLD 4148737
#define UNITY_VERSION_DATE 1615958315
#define UNITY_VERSION_WIN "2019.4.23.4148737"
#define UNITY_VERSION_BRANCH "2019.4/staging"
